spring:
  application:
    name: spring-cloud-service-eureka-provider
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: false
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.4.3:30013/datasource?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: password
      initial-size: 20
      max-active: 50
      min-idle: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      remove-abandoned-timeout: 1800
      remove-abandoned: true
      validation-query: "select 1"
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      default-auto-commit: false
      query-timeout: 15

mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
#每间隔2s，向服务端发送一次心跳，证明自己依然"存活"
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s之内没有给你发心跳，就代表我故障了，将我踢出掉
    lease-expiration-duration-in-seconds: 10
    #告诉服务端，服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    #告诉服务端，服务实例的名字
    instance-id: ${spring.application.name}
  #eureka注册中心的连接地址
  client:
    service-url:
      defaultZone: http://spring-cloud-service-eureka:8761/eureka

